### ISSUE TITLE
Emmet predictions in php context take precedence over php snippets.

### ISSUE THREAD

**Issue by VesterDe** [emmetio/atom-plugin#17]
This may be true in other contexts as well, but in php, emmet takes precedence before my own snippets.

![example](https://cloud.githubusercontent.com/assets/722505/25935766/f7b99a3e-3624-11e7-8651-fb940d499995.png)
In the image, I want my write_log snippet to expand, not the `<wl></wl>` element.

I don't (ever?) want emmet expansion to happen in php context. Or even if I did, I would want my snippets to be primary.

Is this a priority setting or something similar?

**Comment by sergeche** [comment]
Yes, snippets precedence is controlled by priority in autocomplete provider. It this case, you shouldn’d see automatic abbreviation preview at all, only in case of manually invoked autocomplete popup. I need some time and experiments to tweak such behaviour.
