### ISSUE TITLE
Emmet abbreviation with (...)*n doesn't work

### ISSUE THREAD

**Issue by ramya-rao-a** [emmetio/atom-plugin#23]
See https://github.com/Microsoft/vscode/issues/27784

Same happens in the atom plugin as well

**Comment by ramya-rao-a** [comment]
@sergeche ping

**Comment by sergeche** [comment]
Will take a look when I have time

**Comment by ramya-rao-a** [comment]
@sergeche I have submitted a PR for this

https://github.com/emmetio/output-renderer/issues/1

**Comment by ramya-rao-a** [comment]
Fixed with https://github.com/emmetio/output-renderer/commit/45b51e60410652fd1aaf914201fd1ab4c18283b1
