### ISSUE TITLE
Few of the abbreviations from the cheatsheet don't work

### ISSUE THREAD

**Issue by ramya-rao-a** [emmetio/atom-plugin#27]
From the [cheatsheet](https://docs.emmet.io/cheat-sheet/)

- Abbreviations with @ like `ul>li.item$@-*5` and  `ul>li.item$@3*5`
- doc4
- html:4t or !!!4t
- html:4s or !!!4s
- html:xt or !!!4xt
- html:xs or !!!4xs
- html:xxs or !!!4xxs
- all the alias with + in the end like ol+ ul+ table+ etc

**Comment by ramya-rao-a** [comment]
https://github.com/ramya-rao-a/abbreviation/commit/5d875fa80d77d6b76ccac4cc8b5300dc8b99fa58 is my proposal for supporting abbreviations ending with + like `select+`, `ul+` etc

https://github.com/emmetio/snippets/pull/1/files/9efe5d3cc2e4272a6ca7d65ef1bb7978c8a790a6#r128973621 is the ensuing discussion around the same.

**Comment by ramya-rao-a** [comment]
@sergeche Any reasons you didn't include the below from the emmet cheatsheet in the html snippets?

- doc4
- html:4t or !!!4t
- html:4s or !!!4s
- html:xt or !!!4xt
- html:xs or !!!4xs
- html:xxs or !!!4xxs

**Comment by sergeche** [comment]
These snippets are very obsolete these days

**Comment by ramya-rao-a** [comment]
I'll close this issue then.

Logged https://github.com/emmetio/html-transform/issues/2 for the `@-` issue
Logged https://github.com/emmetio/html-matcher/issues/1 for the snippets ending with `+` issue
