### ISSUE TITLE
Autocomplete is trigger incorrectly within Vue templates when using Stylus

### ISSUE THREAD

**Issue by Phunky** [emmetio/atom-plugin#33]
![image](https://user-images.githubusercontent.com/67351/29946620-f9b7238e-8e9d-11e7-87b5-3912f915c918.png)

![image](https://user-images.githubusercontent.com/67351/29946678-24f7ebdc-8e9e-11e7-9c77-4d3417dc3040.png)

![image](https://user-images.githubusercontent.com/67351/29946687-2afffbbe-8e9e-11e7-8d72-781d4928fbce.png)

Writing any selector will trigger the autocomplete to show in Vue templates, I can confirm it's fine for actual Stylus files, but when uses within a Vue Component it seems to get confused.

Can CSS completions be disabled, i've never really used them so being able to disable them would allow me to keep using emmet :D otherwise it's a bit of a nightmare to work with Vue components.

**Comment by sergeche** [comment]
I’m not familiar with Vue. What do you write inside `<style lang="stylus">`, what the expected behaviour?

**Comment by Phunky** [comment]
It's just CSS using the Stylus preprocessor syntax, i'd expect it to be handled the same as `.styl` files are handled.

**Comment by sergeche** [comment]
It seems like it already works as expected: `display inline` is a stylesheet completion in Stylus dialect

**Comment by Phunky** [comment]
`display: inline` is valid CSS property, but it's autocompleting while i'm writing the selector in the screenshots above.

Stylus has the ability to write with a minimal syntax that similar to what you can do in `scss`

```
.selector {
 display: inline
}
// Can be written like
.selector
 display inline
```

**Comment by ipkpjersi** [comment]
I agree with this issue, I think being able to disable this feature would be good to have.
