### ISSUE TITLE
HTML tags missing last character

### ISSUE THREAD

**Issue by stevgouws** [emmetio/atom-plugin#34]
Hi, I have a very weird issue where the autocomplete for html tags are always missing the last character of the word. If I write `div` it autocompletes to `<di></di>`. It's the same for any tag.

![image](https://user-images.githubusercontent.com/13498291/34196775-382ab160-e56c-11e7-8a32-d4b62e15243e.png)

If I hit ctrl + space then it fixes it.

![image](https://user-images.githubusercontent.com/13498291/34196929-db50f764-e56c-11e7-866a-1a1001271709.png)

I'm on Atom 1.23.1 on Mac. It started happening after I ran out of disk space, Atom said "Failed to save config.cson" and I lost all my settings. I've since restored from config.cson from like a month ago, tried reinstalling emmet, tried reinstalling atom completely. But no luck.

I see now the same happens if I try to get completions for stylus, but in this case it doesn't show anything. Then I hit ctrl + space and it shows me the options I want.

No idea if this is related to the error with config I got, or Atom version or what but emmet was working perfectly before. Any help/advice pointing in the right direction would be appreciated.

**Comment by sergeche** [comment]
Did you tried a complete Atom re-install? Might be `autocomplete-plus` is fails to properly poll Emmet provider when editor content changes

**Comment by stevgouws** [comment]
Yeah I deleted everything in .atom and atom.app and reinstalled but still the same. Should I try the same but also delete all the atom files in the Library folders etc?

**Comment by sergeche** [comment]
Try to disable all other third-party plugins and restart Atom. Just checked on latest Atom 1.23.1 — everything seems to work fine

**Comment by stevgouws** [comment]
Okay, disabled literally everything apart from base packages, restarted and still the same.

I noticed though it works for basic html template with `!`

![image](https://user-images.githubusercontent.com/13498291/34199041-14ad38ee-e575-11e7-8e93-f5c64d6a9538.png)

**Comment by sergeche** [comment]
Maybe there are error in Atom DevTools?

**Comment by stevgouws** [comment]
Only a warning from Treeview

![image](https://user-images.githubusercontent.com/13498291/34199509-acdec99c-e576-11e7-83f0-39825bf08d45.png)

**Comment by stevgouws** [comment]
By the way, if I add a class name it happens with the class name not the tag.

![image](https://user-images.githubusercontent.com/13498291/34200262-145b6fce-e579-11e7-855d-e9cf2a85ad00.png)

**Comment by tbnv** [comment]
I have the same issue with SASS/SCSS files, it's not just HTML. There is always 1 character missing.

For example:
![klmnksnlao](https://user-images.githubusercontent.com/1021579/34300828-3ecf452a-e72a-11e7-8a86-1dfdd35189b2.gif)

**Comment by sergeche** [comment]
That’s weird. Can you post your OS/Atom version and list of plugins?

**Comment by tbnv** [comment]
Here you are:

macOS 10.13.2
Atom 1.21.1

Packages:
* atom-increment@0.3.4
* atom-snazzy-clear-syntax@0.5.5
* city-lights-icons@1.1.1
* city-lights-syntax@1.1.4
* city-lights-ui@1.3.0
* language-typescript-grammars-only@1.6.0
* less-than-slash@0.17.0
* new-file-plus@0.2.1
* project-manager@3.3.5
* sort-lines@0.18.0
* sync-settings@0.8.3
* tree-view-copy-relative-path@1.2.0* 
* emmet-atom-plugin@0.0.1

**Comment by tbnv** [comment]
@sergeche Any idea about how to work around this? I'm so used to this plugin and nomenclature, now that it's broken I write more mistakes than good code. 🙁

**Comment by sergeche** [comment]
@tbnv had no time to look at this issue yet, will check it out asap

**Comment by ohiosveryown** [comment]
Same issues as @tbnv and @stevgouws – Atom 1.23.1 on Mac.

**Comment by tbnv** [comment]
@sergeche Sorry but is there any chance you could have a look at it anytime soon? Correcting auto-complete mistakes is so time-consuming… 🙁

**Comment by sergeche** [comment]
Just pushed update, should fix this issue

**Comment by stevgouws** [comment]
0.1 works for me, thanks a lot.

**Comment by tbnv** [comment]
@sergeche Many thanks!
