### ISSUE TITLE
Loading autocomplete suggestion from other plugins

### ISSUE THREAD

**Issue by mrleblanc101** [emmetio/atom-plugin#35]
Hi,
I don't know if it's normal, but this version of emmet does not load autocomplete suggestions (snippets) from other package (language/syntax). For exemple in emmetio/emmet-atom, i have a bunch of autocomplete suggestions for twig.

**Comment by mrleblanc101** [comment]
Or maybe i figured it out, i need to enable both plugin (?)

**Comment by sergeche** [comment]
New plugin is a replacement for old one. Currently, it doesn’t support custom snippets, it used mostly to test new UX model of Emmet. When released, you’ll be able to easily create, store & sync your settings via web-service
