### ISSUE TITLE
Margin auto (m:a) expansion doesn't work

### ISSUE THREAD

**Issue by VesterDe** [emmetio/atom-plugin#4]
m:a + tab does nothing (it doesn't indicate anything wants to happen at all, via autocomplete+).

Is this a bug or is my setup being faulty?

EDIT: Testing a bit more shows it is in fact all rules containing a colon that don't work.

**Comment by sergeche** [comment]
Looks like a bug, doesn’t work for me neither. You can try `m-a` instead

**Comment by VesterDe** [comment]
Ah yeah, that works. Thanks!

**Comment by sergeche** [comment]
Will be fixed in next update
