### ISSUE TITLE
Bug with Enter key

### ISSUE THREAD

**Issue by PsyEnmanuel** [emmetio/atom-plugin#8]
this plugin is messing with the normal functionality of the key enter, like double space when hitting enter, and not getting auto suggestions.

**Comment by sergeche** [comment]
Could you provide code snippet and document syntax when it happens? Enter key should work only when caret between `><`

**Comment by PsyEnmanuel** [comment]
I recorded it, i hope you can see, when i click enter on the editor, it jump 2 lines. 

![bug-emmet](https://cloud.githubusercontent.com/assets/24580192/25099914/2c451226-237c-11e7-8762-49a92c9fc2a3.gif)

**Comment by sergeche** [comment]
I see you have lots of errors. Could you please post a stack trace or create a new issue, as proposed by Atom in error message?

**Comment by sergeche** [comment]
Also, which syntax package you are using?

**Comment by PsyEnmanuel** [comment]
i didn't have those others errors the first time i installed it, i haven't studied the reason of them yet. The package i am using atm are:
atom-jade
atom-ternjs
emmet
emmet-snippets-compatibility
language-vue
nodejs.snippets

**Comment by sergeche** [comment]
Can you try to disable both `emmet` and `emmet-snippets-compatibility` packages&

**Comment by PsyEnmanuel** [comment]
i did uninstall both
and the bug with enter key disapear,
i installed emmet, again and the bug appeared again.

I opened a .jade, .css, .sass files and the bug disappeared.
it seems it only appear on .vue files when emmet and emmetio/atom-plugin are installed

and then i made more test, and while emmet and emmetio/atom-plugin installed y uninstalled vue-language and the bug disappeared.

Resuming. the problem happens with .vue files, and when vue-language package is installed.

**Comment by sergeche** [comment]
Both `emmet` and `emmet-atom-plugin` implements the same feature with formatted line break. You should you only one plugin

**Comment by PsyEnmanuel** [comment]
thanks, i bealive, i can work around it.
